### ISSUE TITLE
Cargo test fails  'couldn't spawn maidsafe_vault: os error', tests/lib.rs:44

### ISSUE THREAD

**Issue by southsideGLA** [maidsafe/maidsafe_vault#132] opened 2015-06-29 21:18 UTC
latest git pull fails  cargo test

 Running `/home/willie/projects/maidSafe/maidsafe_vault/target/release/lib-92d38e5b3eab1a12`

running 1 test
test executable_test ... FAILED

failures:

---- executable_test stdout ----
        ---------- starting node 0 --------------
thread 'executable_test' panicked at 'couldn't spawn maidsafe_vault: os error', tests/lib.rs:44

failures:
    executable_test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

Last nights rust, all latest git updates.
Command was
cargo test --release --verbose | tee m_vault.log 

m_vault.log is available at (http://maidsafe.wf.tsone.info/fault-logs/m_vault.log)
At 29K its too big to paste here.

**Comment by maqi** [comment] 2015-06-30 08:38
this test requires an executable maidsafe_vault to be presented already.
you will need to run "cargo build" first to generate the executable, before executing "cargo test"

**Comment by Fraser999** [comment] 2015-06-30 08:42
Can we provide a meaningful failure message in the case that the exe isn't available please?

**Comment by maqi** [comment] 2015-06-30 09:05
ok, the issue is because of the test was run in release mode and the testing code only looking for the executable under the debug folder.
I am creating a PR telling the test to be executed in debug mode,
however, not sure whether / how we can also cover the release case.

**Comment by dirvine** [comment] 2015-06-30 09:16
Perhaps get current path of the test exe and regex for target/release or target/debug than look for the vault exe in the correct place. If not found exit with a meaningful error message, stating vault must be built using (cargo build [--release] etc.)

**Comment by maqi** [comment] 2015-06-30 10:03
Resolving in PR https://github.com/maidsafe/maidsafe_vault/pull/133

**Comment by southsideGLA** [comment] 2015-06-30 10:14
doh!  normally I run the following for each ccrate


git pull && cargo clean --verbose && cargo update --verbose && cargo build  && cargo test --release --verbose | tee update.log

but checking the history it seems I only did  a git pull on this cooasion - sorry for the hassle

**Closed** 2015-07-02 12:07 UTC
